// react-next-demo/app/page.tsx
'use client'

import { useState } from 'react'
import { useLocalStorage } from './hooks/useLocalStorage'

type Cell = 'X' | 'O' | null

interface Score {
  X: number
  O: number
  draws: number
}

const WINNING_COMBINATIONS: [number, number, number][] = [
  [0, 1, 2], [3, 4, 5], [6, 7, 8],
  [0, 3, 6], [1, 4, 7], [2, 5, 8],
  [0, 4, 8], [2, 4, 6],
]

function checkWinner(board: Cell[]): 'X' | 'O' | null {
  for (const [a, b, c] of WINNING_COMBINATIONS) {
    if (board[a] && board[a] === board[b] && board[a] === board[c]) {
      return board[a] as 'X' | 'O'
    }
  }
  return null
}

function cellClass(cell: Cell): string {
  if (!cell) return 'btn btn-outline-secondary fw-bold fs-2 m-1'
  return cell === 'X'
    ? 'btn btn-primary fw-bold fs-2 m-1'
    : 'btn btn-danger fw-bold fs-2 m-1'
}

export default function Home() {
  const [board, setBoard] = useState<Cell[]>(Array(9).fill(null))
  const [currentPlayer, setCurrentPlayer] = useState<'X' | 'O'>('X')
  const [gameOver, setGameOver] = useState(false)
  const [winner, setWinner] = useState<'X' | 'O' | null>(null)
  const [score, setScore] = useLocalStorage<Score>('tictactoe-score', { X: 0, O: 0, draws: 0 })

  function handleClick(index: number) {
    if (gameOver || board[index]) return

    const newBoard = [...board]
    newBoard[index] = currentPlayer
    setBoard(newBoard)

    const w = checkWinner(newBoard)
    if (w) {
      setWinner(w)
      setGameOver(true)
      setScore({ ...score, [w]: score[w] + 1 })
    } else if (newBoard.every(Boolean)) {
      setGameOver(true)
      setScore({ ...score, draws: score.draws + 1 })
    } else {
      setCurrentPlayer(currentPlayer === 'X' ? 'O' : 'X')
    }
  }

  function newGame() {
    setBoard(Array(9).fill(null))
    setCurrentPlayer('X')
    setGameOver(false)
    setWinner(null)
  }

  function resetScore() {
    setScore({ X: 0, O: 0, draws: 0 })
    newGame()
  }

  function statusMessage() {
    if (winner) return `¡Gana ${winner}!`
    if (gameOver) return '¡Empate!'
    return `Turno de ${currentPlayer}`
  }

  function statusClass() {
    if (winner === 'X') return 'badge fs-5 px-4 py-2 bg-primary'
    if (winner === 'O') return 'badge fs-5 px-4 py-2 bg-danger'
    if (gameOver) return 'badge fs-5 px-4 py-2 bg-secondary'
    return currentPlayer === 'X'
      ? 'badge fs-5 px-4 py-2 bg-primary'
      : 'badge fs-5 px-4 py-2 bg-danger'
  }

  return (
    <div className="container py-4">
      <h1 className="text-center mb-4">Tres en Raya</h1>

      <div className="d-flex flex-column align-items-center mb-3">
        {[0, 1, 2].map((row) => (
          <div key={row} className="d-flex">
            {[0, 1, 2].map((col) => {
              const index = row * 3 + col
              return (
                <button
                  key={col}
                  className={cellClass(board[index])}
                  style={{ width: 90, height: 90 }}
                  onClick={() => handleClick(index)}
                >
                  {board[index]}
                </button>
              )
            })}
          </div>
        ))}
      </div>

      <div className="text-center mb-3">
        <span className={statusClass()}>{statusMessage()}</span>
      </div>

      <div className="text-center mb-4">
        <button className="btn btn-success me-2" onClick={newGame}>
          Nueva partida
        </button>
        <button className="btn btn-outline-secondary" onClick={resetScore}>
          Resetear marcador
        </button>
      </div>

      <div className="row justify-content-center g-3 text-center">
        <div className="col-auto">
          <div className="card" style={{ minWidth: 110 }}>
            <div className="card-body">
              <h5 className="card-title text-primary">X</h5>
              <p className="display-5 mb-0">{score.X}</p>
            </div>
          </div>
        </div>
        <div className="col-auto">
          <div className="card" style={{ minWidth: 110 }}>
            <div className="card-body">
              <h5 className="card-title text-secondary">Empates</h5>
              <p className="display-5 mb-0">{score.draws}</p>
            </div>
          </div>
        </div>
        <div className="col-auto">
          <div className="card" style={{ minWidth: 110 }}>
            <div className="card-body">
              <h5 className="card-title text-danger">O</h5>
              <p className="display-5 mb-0">{score.O}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// angular-demo/src/app/app.ts
import { Component, computed, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { StorageService } from './services/storage.service';

type Cell = 'X' | 'O' | null;

interface Score {
  X: number;
  O: number;
  draws: number;
}

const WINNING_COMBINATIONS: [number, number, number][] = [
  [0, 1, 2], [3, 4, 5], [6, 7, 8],
  [0, 3, 6], [1, 4, 7], [2, 5, 8],
  [0, 4, 8], [2, 4, 6],
];

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './app.html',
  styleUrl: './app.scss',
})
export class App {
  private storage = inject(StorageService);

  board = signal<Cell[]>(Array(9).fill(null));
  currentPlayer = signal<'X' | 'O'>('X');
  gameOver = signal(false);
  winner = signal<'X' | 'O' | null>(null);
  score = signal<Score>(this.storage.get<Score>('tictactoe-score', { X: 0, O: 0, draws: 0 }));

  rows = [0, 1, 2];
  cols = [0, 1, 2];

  statusMessage = computed(() => {
    if (this.winner()) return `¡Gana ${this.winner()}!`;
    if (this.gameOver()) return '¡Empate!';
    return `Turno de ${this.currentPlayer()}`;
  });

  statusClass = computed(() => {
    if (this.winner() === 'X') return 'bg-primary';
    if (this.winner() === 'O') return 'bg-danger';
    if (this.gameOver()) return 'bg-secondary';
    return this.currentPlayer() === 'X' ? 'bg-primary' : 'bg-danger';
  });

  cellClass(cell: Cell): string {
    if (!cell) return 'btn-outline-secondary';
    return cell === 'X' ? 'btn-primary' : 'btn-danger';
  }

  private checkWinner(b: Cell[]): 'X' | 'O' | null {
    for (const [a, c, d] of WINNING_COMBINATIONS) {
      if (b[a] && b[a] === b[c] && b[a] === b[d]) return b[a] as 'X' | 'O';
    }
    return null;
  }

  handleClick(index: number): void {
    if (this.gameOver() || this.board()[index]) return;

    const newBoard = [...this.board()];
    newBoard[index] = this.currentPlayer();
    this.board.set(newBoard);

    const w = this.checkWinner(newBoard);
    if (w) {
      this.winner.set(w);
      this.gameOver.set(true);
      const newScore = { ...this.score(), [w]: this.score()[w] + 1 };
      this.score.set(newScore);
      this.storage.set('tictactoe-score', newScore);
    } else if (newBoard.every(Boolean)) {
      this.gameOver.set(true);
      const newScore = { ...this.score(), draws: this.score().draws + 1 };
      this.score.set(newScore);
      this.storage.set('tictactoe-score', newScore);
    } else {
      this.currentPlayer.set(this.currentPlayer() === 'X' ? 'O' : 'X');
    }
  }

  newGame(): void {
    this.board.set(Array(9).fill(null));
    this.currentPlayer.set('X');
    this.gameOver.set(false);
    this.winner.set(null);
  }

  resetScore(): void {
    const empty: Score = { X: 0, O: 0, draws: 0 };
    this.score.set(empty);
    this.storage.set('tictactoe-score', empty);
    this.newGame();
  }
}
