// vue-demo/src/components/GameBoard.vue
<script setup>
import GameCell from './GameCell.vue'

// 'board': array de 9 posiciones con los valores del tablero.
// 'statusMessage': texto del badge ("Turno de X", "¡Gana O!", etc.).
// 'statusClass': clase Bootstrap del badge ('bg-primary', 'bg-danger', etc.).
defineProps({
  board: {
    type: Array,
    required: true,
  },
  statusMessage: {
    type: String,
    required: true,
  },
  statusClass: {
    type: String,
    required: true,
  },
})

// Cuando el usuario pulsa una celda, este componente emite 'cell-click'
// con el índice de la casilla. El padre (HomeView) es quien actualiza el estado.
const emit = defineEmits(['cell-click'])
</script>

<template>
  <div class="d-flex flex-column align-items-center mb-3">
    <div v-for="row in [0, 1, 2]" :key="row" class="d-flex">
      <!-- Pasamos el valor de la celda como prop ':cell'.
           Escuchamos el evento 'click' del hijo y lo re-emitimos hacia HomeView
           con el índice calculado. -->
      <GameCell
        v-for="col in [0, 1, 2]"
        :key="col"
        :cell="board[row * 3 + col]"
        @click="emit('cell-click', row * 3 + col)"
      />
    </div>
  </div>

  <div class="text-center mb-3">
    <span class="badge fs-5 px-4 py-2" :class="statusClass">
      {{ statusMessage }}
    </span>
  </div>
</template>

// angular-demo/src/app/components/game-board/game-board.component.ts
import { Component, input, output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { GameCellComponent } from '../game-cell/game-cell.component';
import { Cell } from '../../models/game.types';

@Component({
  selector: 'app-game-board',
  standalone: true,
  imports: [CommonModule, GameCellComponent],
  template: `
    <div class="d-flex flex-column align-items-center mb-3">
      <div *ngFor="let row of rows" class="d-flex">
        <!-- Pasamos el valor de cada celda como input 'cell'.
             Escuchamos el evento 'clicked' del hijo y emitimos 'cellClick'
             hacia AppComponent con el índice calculado. -->
        <app-game-cell
          *ngFor="let col of cols"
          [cell]="board()[row * 3 + col]"
          (clicked)="cellClick.emit(row * 3 + col)"
        />
      </div>
    </div>

    <div class="text-center mb-3">
      <!-- [ngClass] aplica la clase Bootstrap del badge dinámicamente según el estado. -->
      <span class="badge fs-5 px-4 py-2" [ngClass]="statusClass()">
        {{ statusMessage() }}
      </span>
    </div>
  `,
})
export class GameBoardComponent {
  // 'board': array de 9 posiciones con los valores actuales del tablero.
  board = input.required<Cell[]>();
  // 'statusMessage': texto informativo del turno o resultado.
  statusMessage = input.required<string>();
  // 'statusClass': clase Bootstrap del badge ('bg-primary', 'bg-danger', etc.).
  statusClass = input.required<string>();

  // Evento que sube el índice de la celda pulsada hasta AppComponent.
  cellClick = output<number>();

  rows = [0, 1, 2];
  cols = [0, 1, 2];
}
