// angular-demo/src/app/components/game-cell/game-cell.component.ts
import { Component, input, output, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Cell } from '../../models/game.types';

@Component({
  selector: 'app-game-cell',
  standalone: true,
  imports: [CommonModule],
  template: `
    <!-- Emitimos el evento 'clicked' al padre cuando el usuario pulsa la celda.
         El padre (GameBoard) añadirá el índice y re-emitirá hacia AppComponent. -->
    <button
      class="btn m-1 fw-bold fs-2"
      [ngClass]="cellClass()"
      style="width: 90px; height: 90px;"
      (click)="clicked.emit()"
    >
      {{ cell() }}
    </button>
  `,
})
export class GameCellComponent {
  // input() es la API de señales de Angular 21 para recibir datos del padre.
  // 'cell' recibe el valor de la casilla: 'X', 'O' o null.
  cell = input<Cell>(null);

  // output() declara un evento que este componente puede emitir hacia el padre.
  // El padre escucha con (clicked)="onCellClicked(i)".
  clicked = output<void>();

  cellClass = computed(() => {
    if (!this.cell()) return 'btn-outline-secondary';
    return this.cell() === 'X' ? 'btn-primary' : 'btn-danger';
  });
}

// vue-demo/src/components/GameCell.vue
<script setup>
// defineProps declara las propiedades que el componente padre puede pasarle.
// 'cell' es el valor de la casilla: 'X', 'O' o null (casilla vacía).
const props = defineProps({
  cell: {
    type: String,
    default: null,
  },
})

// defineEmits declara los eventos que este componente puede emitir hacia el padre.
// El padre escuchará este evento con @click="handleClick(index)".
const emit = defineEmits(['click'])

function cellClass() {
  if (!props.cell) return 'btn-outline-secondary'
  return props.cell === 'X' ? 'btn-primary' : 'btn-danger'
}
</script>

<template>
  <!-- Al hacer clic, emitimos el evento 'click' hacia el componente padre.
       El padre decide qué hacer con él (tiene el índice en contexto). -->
  <button
    class="btn m-1 fw-bold fs-2"
    :class="cellClass()"
    style="width: 90px; height: 90px;"
    @click="emit('click')"
  >
    {{ cell }}
  </button>
</template>
