// react-next-demo/app/components/GameScoreboard.tsx
'use client'

import { Score } from '../types/game'

// 'score': objeto con las victorias de X, O y los empates.
// Este componente es puramente presentacional: recibe datos y los muestra.
// No emite ningún evento ni modifica estado.
interface GameScoreboardProps {
  score: Score
}

export default function GameScoreboard({ score }: GameScoreboardProps) {
  return (
    <div className="row justify-content-center g-3 text-center">
      <div className="col-auto">
        <div className="card" style={{ minWidth: 110 }}>
          <div className="card-body">
            <h5 className="card-title text-primary">X</h5>
            <p className="display-5 mb-0">{score.X}</p>
          </div>
        </div>
      </div>
      <div className="col-auto">
        <div className="card" style={{ minWidth: 110 }}>
          <div className="card-body">
            <h5 className="card-title text-secondary">Empates</h5>
            <p className="display-5 mb-0">{score.draws}</p>
          </div>
        </div>
      </div>
      <div className="col-auto">
        <div className="card" style={{ minWidth: 110 }}>
          <div className="card-body">
            <h5 className="card-title text-danger">O</h5>
            <p className="display-5 mb-0">{score.O}</p>
          </div>
        </div>
      </div>
    </div>
  )
}

// vue-demo/src/components/GameScoreboard.vue
<script setup>
// 'score' es un objeto reactivo pasado desde HomeView con las victorias
// de cada jugador y los empates. Al ser una prop, se actualiza automáticamente
// cuando el padre modifica el valor.
defineProps({
  score: {
    type: Object,
    required: true,
  },
})
</script>

<template>
  <div class="row justify-content-center g-3 text-center">
    <div class="col-auto">
      <div class="card" style="min-width: 110px;">
        <div class="card-body">
          <h5 class="card-title text-primary">X</h5>
          <p class="display-5 mb-0">{{ score.X }}</p>
        </div>
      </div>
    </div>
    <div class="col-auto">
      <div class="card" style="min-width: 110px;">
        <div class="card-body">
          <h5 class="card-title text-secondary">Empates</h5>
          <p class="display-5 mb-0">{{ score.draws }}</p>
        </div>
      </div>
    </div>
    <div class="col-auto">
      <div class="card" style="min-width: 110px;">
        <div class="card-body">
          <h5 class="card-title text-danger">O</h5>
          <p class="display-5 mb-0">{{ score.O }}</p>
        </div>
      </div>
    </div>
  </div>
</template>
