// vue-demo/src/components/GameControls.vue
<script setup>
// Este componente no necesita ningún dato del padre.
// Solo emite eventos para que HomeView ejecute las acciones correspondientes.
const emit = defineEmits(['new-game', 'reset-score'])
</script>

<template>
  <div class="text-center mb-4">
    <!-- Al pulsar, emitimos 'new-game'. HomeView escucha con @new-game="newGame()". -->
    <button class="btn btn-success me-2" @click="emit('new-game')">
      Nueva partida
    </button>
    <!-- Al pulsar, emitimos 'reset-score'. HomeView escucha con @reset-score="resetScore()". -->
    <button class="btn btn-outline-secondary" @click="emit('reset-score')">
      Resetear marcador
    </button>
  </div>
</template>

// react-next-demo/app/components/GameControls.tsx
'use client'

// Props de GameControls: solo callbacks, no necesita datos de estado.
// 'onNewGame': función a ejecutar al pulsar "Nueva partida".
// 'onResetScore': función a ejecutar al pulsar "Resetear marcador".
// Este patrón de pasar callbacks como props es la forma estándar en React
// para que componentes hijos desencadenen acciones en el padre.
interface GameControlsProps {
  onNewGame: () => void
  onResetScore: () => void
}

export default function GameControls({ onNewGame, onResetScore }: GameControlsProps) {
  return (
    <div className="text-center mb-4">
      <button className="btn btn-success me-2" onClick={onNewGame}>
        Nueva partida
      </button>
      <button className="btn btn-outline-secondary" onClick={onResetScore}>
        Resetear marcador
      </button>
    </div>
  )
}
