// angular-demo/src/app/components/game-cell/game-cell.component.ts
import { Component, input, output, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Cell } from '../../models/game.types';

@Component({
  selector: 'app-game-cell',
  standalone: true,
  imports: [CommonModule],
  template: `
    <!-- Emitimos el evento 'clicked' al padre cuando el usuario pulsa la celda.
         El padre (GameBoard) añadirá el índice y re-emitirá hacia AppComponent. -->
    <button
      class="btn m-1 fw-bold fs-2"
      [ngClass]="cellClass()"
      style="width: 90px; height: 90px;"
      (click)="clicked.emit()"
    >
      {{ cell() }}
    </button>
  `,
})
export class GameCellComponent {
  // input() es la API de señales de Angular 21 para recibir datos del padre.
  // 'cell' recibe el valor de la casilla: 'X', 'O' o null.
  cell = input<Cell>(null);

  // output() declara un evento que este componente puede emitir hacia el padre.
  // El padre escucha con (clicked)="onCellClicked(i)".
  clicked = output<void>();

  cellClass = computed(() => {
    if (!this.cell()) return 'btn-outline-secondary';
    return this.cell() === 'X' ? 'btn-primary' : 'btn-danger';
  });
}

// react-router-demo/app/components/GameCell.tsx
import type { Cell } from '../types/game'

// Props que recibe GameCell desde GameBoard.
// 'cell': valor de la casilla ('X', 'O' o null).
// 'onCellClick': callback que GameBoard ejecutará cuando el usuario pulse.
//   En React los eventos se propagan hacia arriba pasando funciones como props.
interface GameCellProps {
  cell: Cell
  onCellClick: () => void
}

function cellClass(cell: Cell): string {
  if (!cell) return 'btn btn-outline-secondary fw-bold fs-2 m-1'
  return cell === 'X'
    ? 'btn btn-primary fw-bold fs-2 m-1'
    : 'btn btn-danger fw-bold fs-2 m-1'
}

export default function GameCell({ cell, onCellClick }: GameCellProps) {
  return (
    // onCellClick es una función que nos pasa el padre (GameBoard).
    // Al pulsarla, React la ejecuta y el control sube al componente padre.
    <button
      className={cellClass(cell)}
      style={{ width: 90, height: 90 }}
      onClick={onCellClick}
    >
      {cell}
    </button>
  )
}
